### ISSUE TITLE
Server is crashing

### ISSUE THREAD

**Issue by Akuroma** [ServerSoftwareOrg/Tesseract#1]
#### Problem description
Server is crashing.

#### Steps to reproduce the issue
Add the filfe which is shown in the crashdump.

#### OS and versions

* Tesseract: Version: 1.2.0, Protocol: 107, Codename: Ruby, MCPE: 1.0.7
* PHP: 3.0.1
* Server OS: Linux, Ubuntu 14.04
* Game version: 1.0.7 (Android and Win10)
* Server host: Virtual Server
<br><br>
#### Crashdump, backtrace, memory dumps, plugins list or other files
![image](https://cloud.githubusercontent.com/assets/19476909/25280547/a33140e0-26aa-11e7-96b2-c70428b789d7.png)
```
```

**Comment by caspervanneck** [comment]
fixt at 9a67dcc  @Akuroma
